---
title: "Data_Transformation"
author: "DA101"
date: "2025-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install packages nycflights13 and tidyverse


```


```{r}
#load data set: flights


```


```{r}
#filter our data set to January 1


```


```{r}
#Create a new data set called jan1 by filtering flights to January 1

```


```{r}
#Create a new data set called dec31 by filtering flights to December 31


```


```{r}
#Find all flights that departed in November OR December


```


```{r}
#Find all flights that were not delayed (on arrival or departure) by more than two hours (120 minutes)


```


```{r}
#Arrange rows of the data set flights


#Reorder the column dep_delay in descending order

```


```{r}
#Select columns year, month, and day

```


```{r}
#Rename tail_num to tailnum

```


```{r}
#Summarise flights to calculate the mean of dep_delay


```


```{r}
#Calculate the mean dep_delay; group by month


```

